### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by aitchbi** [StuartJO/plotSurfaceROIBoundary#3]
Hi Stuart. Thanks for this helpful repository. I checked `demo_ExampleSurfacePlotFunction.m`, which runs into error on line 16. Variable `lh_HCPMMP1_gene_pc1` is missing, apparently missed out when you saved the `example_data.mat`.

**Comment by StuartJO** [comment]
Hi, thanks for noticing! It should now have been added now to example_data.mat.
