### ISSUE TITLE
aparc.a2009s.annot support issue

### ISSUE THREAD

**Issue by ChenK19** [StuartJO/plotSurfaceROIBoundary#4]
Hi,
Your visualization tool is prettey useful! 
But i meet an problem while using your plotsurface example, there are only aparc and HCPMMP1 parcellation, I hope to add the aparc.a2009s ROI as an 163842x1 double matrix(follow your example), or could you please update this file in the future into your 'surface_data.mat', cause that's too difficult for me..
Thanks for your any reply.

**Comment by StuartJO** [comment]
Hi,
If you have the .annot file you can use the read_annotation function to read it into MATLAB. Check out the example in demo_ExampleSurfacePlotFunction.m for how to get this data into the right format. Hopefully it is straightforward!
Kind regards,
Stuart

**Comment by ChenK19** [comment]
Thanks for your reply, i think my problem is solved.

**Comment by StuartJO** [comment]
Glad to hear! :)
